name: moodify_mobile
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8
  hugeicons: ^0.0.7
  camera: ^0.11.0+2
  path_provider: ^2.1.5
  path: ^1.9.0
  bloc: ^8.1.4
  http: ^1.2.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/meowdy/
